version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: wedding-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: wedding-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      DB_NAME: weddingDB
    env_file:
      - .env

volumes:
  mongo-data:
